spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201
spring:
  profiles: dev
  application:
    name: micro-service-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://7001.com:7001/eureka/,http://7002.com:7002/eureka/,http://7003.com:7003/eureka/ 
---
server: 
  port: 8202
spring:
  profiles: test
  application:
    name: micro-service-cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://7001.com:7001/eureka/,http://7002.com:7002/eureka/,http://7003.com:7003/eureka/ 