spring:
  profiles:
    active:
    - dev
  application:
    name: micro-service-cloud-eureka-config-client
---
server: 
  port: 7001
spring:
  profiles: dev
  application:
    name: micro-service-cloud-eureka-config-client
eureka:
  client:
    service-url:
      defaultZone: http://7001.com:7001/eureka
  instance:
    instance-id: ureka_config_server_dev
    prefer-ip-address: true      
---
server: 
  port: 7002
spring:
  profiles: test
  application:
    name: micro-service-cloud-eureka-config-client
eureka:
  client:
    service-url:
      defaultZone: http://7001.com:7002/eureka
  instance:
    instance-id: ureka_config_server_test
    prefer-ip-address: true       